import { getRegion } from './regions';
import type { RegionalRecommendation, RiskId } from './types';

export const regionalRecommendations: RegionalRecommendation[] = [
  {
    regionId: 'murcia', sourceId: 'regional-advice-murcia',
    title: 'Linterna y radio preparadas',
    text: 'Antes del periodo de lluvias, deja preparadas una linterna y una radio con pilas cargadas.',
    organization: 'Región de Murcia · Dirección General de Protección Civil',
    url: 'https://conocimientoabierto.carm.es/jspui/bitstream/20.500.11914/2127/4/Anexo%205_Gu%C3%ADa%20de%20consejos%20a%20la%20poblaci%C3%B3n.pdf',
    risks: ['flood'], reviewedAt: '2026-09-05',
    reviewNote: 'INUNMUR, anexo V, página 4, apartado 2.1, punto 2. Texto contrastado con la extracción del repositorio oficial CARM.',
  },
  {
    regionId: 'extremadura', sourceId: 'regional-advice-extremadura',
    title: 'Respeta las restricciones del fuego',
    text: 'Durante la Época de Peligro Alto, no prepares alimentos en el campo mediante barbacoas u hogueras. Consulta el periodo y las restricciones vigentes en el Plan INFOEX.',
    organization: 'Junta de Extremadura · Plan INFOEX',
    url: 'https://www.infoex.info/prevencion-de-actividades-de-riesgo-regulacion-de-usos-y-actividades/',
    risks: ['wildfire'], reviewedAt: '2026-09-05',
  },
  {
    regionId: 'aragon', sourceId: 'regional-advice-aragon',
    title: 'No abandones objetos encendidos',
    text: 'No arrojes ni abandones objetos en combustión en entornos forestales.',
    organization: 'Gobierno de Aragón · Dirección General de Gestión Forestal',
    url: 'https://www.aragonhoy.es/medio-ambiente-turismo/alerta-roja-peligro-incendios-forestales-gran-parte-aragon-sabado-105492',
    risks: ['wildfire'], reviewedAt: '2026-09-05',
    reviewNote: 'Medida preventiva recogida en una nota oficial del 20/06/2026. La alerta de aquella noticia no se presenta como vigente.',
  },
  {
    regionId: 'andalucia', sourceId: 'regional-advice-andalucia',
    title: 'Material básico accesible',
    text: 'Ten a mano una radio, una linterna, un botiquín y tu documentación.',
    organization: 'Junta de Andalucía · Emergencias 112',
    url: 'https://www.juntadeandalucia.es/temas/seguridad/emergencias/que-hacer.html',
    risks: 'general', reviewedAt: '2026-09-05',
  },
  {
    regionId: 'asturias', sourceId: 'regional-advice-asturias',
    title: 'No aparques junto a cauces',
    text: 'No estaciones a la orilla de ríos, en cauces de barrancos o torrentes, ni en sus puentes.',
    organization: 'Principado de Asturias · SEPA / 112',
    url: 'https://www.112asturias.es/inundaciones?npag=1',
    risks: ['flood'], reviewedAt: '2026-09-05',
  },
  {
    regionId: 'baleares', sourceId: 'regional-advice-baleares',
    title: 'Radio, linterna y pilas',
    text: 'Ten en casa una radio, una linterna y pilas de recambio para prepararte ante inundaciones.',
    organization: 'Govern de les Illes Balears · 112',
    url: 'https://apps.caib.es/sites/112/es/en_las_inundaciones_seguros-7002/',
    risks: ['flood'], reviewedAt: '2026-09-05',
  },
  {
    regionId: 'canarias', sourceId: 'regional-advice-canarias',
    title: 'No tires colillas ni cerillas',
    text: 'No tires colillas encendidas ni cerillas, tampoco mientras caminas o desde la ventanilla del coche.',
    organization: 'Gobierno de Canarias · Dirección General de Emergencias',
    url: 'https://www.gobiernodecanarias.org/emergencias/alertas/consejos/incendios/incendios.html',
    risks: ['wildfire'], reviewedAt: '2026-09-05',
  },
  {
    regionId: 'castilla-leon', sourceId: 'regional-advice-castilla-leon',
    title: 'Evita estacionar junto a ríos y torrentes',
    text: 'No aparques a la orilla de ríos, en cauces de barrancos o torrentes, ni en sus puentes.',
    organization: 'Junta de Castilla y León · Emergencias 112',
    url: 'https://112.jcyl.es/web/es/consejos-recomendaciones/inundaciones.html',
    risks: ['flood'], reviewedAt: '2026-09-05',
    reviewNote: 'Texto leído en la versión HTTP oficial. El acceso HTTPS presentó fallos de transporte; se comprueba de nuevo al generar.',
  },
  {
    regionId: 'cantabria', sourceId: 'regional-advice-cantabria',
    title: 'Revisión preventiva de desagües',
    text: 'Comprueba periódicamente el estado de las bajantes de agua y de los desagües próximos a la vivienda.',
    organization: 'Gobierno de Cantabria · Servicio de Emergencias 112',
    url: 'https://112.cantabria.es/consejos-de-autoproteccion/por-fma--fenomenos-meteorologicos-adversos-/lluvias-intensas',
    risks: ['flood'], reviewedAt: '2026-09-05',
  },
  {
    regionId: 'galicia', sourceId: 'regional-advice-galicia',
    title: 'Equipo básico accesible',
    text: 'Ten a mano radio a pilas, linterna, pilas de recambio, medicamentos indispensables, ropa de abrigo y documentación. Renueva las pilas periódicamente.',
    organization: 'Xunta de Galicia · AXEGA / 112 Galicia',
    url: 'https://www.axega112.gal/gl/content/medidas-de-autoproteccion',
    risks: 'general', reviewedAt: '2026-09-05',
  },
  {
    regionId: 'madrid', sourceId: 'regional-advice-madrid',
    title: 'Revisa los desagües antes de las lluvias',
    text: 'Antes de las lluvias intensas, comprueba que las bajadas de agua y los desagües de plantas bajas no estén obstruidos.',
    organization: 'Comunidad de Madrid · ASEM 112',
    url: 'https://www.comunidad.madrid/seguridad-emergencias-asem-112/meteorologia-adversa',
    risks: ['flood'], reviewedAt: '2026-09-05',
  },
  {
    regionId: 'navarra', sourceId: 'regional-advice-navarra',
    title: 'Equipo y documentación a mano',
    text: 'Mantén accesibles una radio, una linterna, un pequeño botiquín y tu documentación.',
    organization: 'Gobierno de Navarra · Seguridad y Emergencias',
    url: 'https://www.navarra.es/es/seguridad-y-emergencias/prevencion-de-riesgos',
    risks: 'general', reviewedAt: '2026-09-05',
  },
  {
    regionId: 'pais-vasco', sourceId: 'regional-advice-pais-vasco',
    title: 'Desagües y objetos arrastrables',
    text: 'Revisa preventivamente los desagües próximos. Retira los objetos que pueda arrastrar el agua, especialmente productos peligrosos capaces de contaminar.',
    organization: 'Gobierno Vasco · Departamento de Seguridad',
    url: 'https://www.euskadi.eus/recomendaciones-meteorologia-adversa/web01-a2larri/es/',
    risks: ['flood'], reviewedAt: '2026-09-05',
  },
  {
    regionId: 'rioja', sourceId: 'regional-advice-rioja',
    title: 'Prepara a los menores para pedir ayuda',
    text: 'Enseña a los niños su nombre, dirección y teléfono, y cómo utilizar el teléfono si necesitan ayuda.',
    organization: 'Gobierno de La Rioja · SOS Rioja 112',
    url: 'https://www.larioja.org/emergencias-112/es/autoproteccion/consejos-autoproteccion/pautas-generales-autoproteccion-prevencion',
    risks: 'general', reviewedAt: '2026-09-05',
  },
  {
    regionId: 'ceuta', sourceId: 'regional-advice-ceuta',
    title: 'Linterna y radio disponibles',
    text: 'Ten en casa una linterna y una radio a pilas para poder informarte durante una emergencia.',
    organization: 'Ciudad Autónoma de Ceuta · ARCE / Protección Civil',
    url: 'https://www.ceuta.es/arce/recomendaciones/generales.html',
    risks: 'general', reviewedAt: '2026-09-05',
  },
  {
    regionId: 'melilla', sourceId: 'regional-advice-melilla',
    title: 'Asegura los muebles pesados',
    text: 'Sujeta firmemente a la pared los muebles pesados. No coloques objetos pesados o frágiles encima de estanterías o muebles similares.',
    organization: 'Ciudad Autónoma de Melilla · Protección Civil',
    url: 'https://www.melilla.es/melillaportal/contenedor.jsp?seccion=s_fdoc_d4_v1.jsp&contenido=22387&nivel=1400&tipo=5&anuncio=1',
    risks: ['earthquake'], reviewedAt: '2026-09-05',
  },
  {
    regionId: 'castilla-mancha', sourceId: 'regional-advice-castilla-mancha',
    title: 'No arrojes cigarrillos desde el vehículo',
    text: 'Apaga bien cerillas y cigarrillos y no los arrojes por las ventanillas del coche.',
    organization: 'Junta de Castilla-La Mancha · Protección Civil',
    url: 'https://112.castillalamancha.es/proteccion-civil/consejos/incendios-forestales',
    risks: ['wildfire'], reviewedAt: '2026-09-05',
  },
  {
    regionId: 'cataluna', sourceId: 'regional-advice-cataluna',
    title: 'Prepara un kit para 72 horas',
    text: 'Ten preparado un kit de emergencias para 72 horas. Consulta los materiales oficiales para adaptarlo a tu hogar.',
    organization: 'Generalitat de Catalunya · Protecció Civil',
    url: 'https://dsp.interior.gencat.cat/handle/20.500.14007/5455',
    risks: 'general', reviewedAt: '2026-09-05',
    reviewNote: 'Consejo verificado en el resumen textual oficial de la campaña; no se han revisado sus documentos adjuntos.',
  },
  {
    regionId: 'valenciana', sourceId: 'regional-advice-valenciana',
    title: 'Botiquín preparado',
    text: 'Mantén preparado un botiquín de primeros auxilios ante posibles inundaciones.',
    organization: 'Generalitat Valenciana · Emergencias 112CV',
    url: 'https://www.112cv.gva.es/va/que-hacer-frente-a-una-inundacion',
    risks: ['flood'], reviewedAt: '2026-09-05',
  },
];

export function getRegionalRecommendations(location: string, risks: RiskId[]) {
  const regionId = getRegion(location)?.id ?? location;
  return regionalRecommendations.filter(item => item.regionId === regionId && (item.risks === 'general' || item.risks.some(risk => risks.includes(risk))));
}
